name: Update Gas Prices

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Run scraper
      run: node scraper.js
    
    - name: Commit and push
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Update prices"
        git push || true
