name: Update Gas Prices

on:
  schedule:
    # Run every 30 minutes from 6 AM to 10 PM EST
    - cron: '*/30 11-3 * * *'  # Adjusted for UTC (EST+5)
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ main ]  # Run when code is pushed

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Run scraper
      run: node scraper.js
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add prices.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update gas prices - $(date '+%Y-%m-%d %H:%M:%S')" && git push)
